export const darkGameAbi = [
  {
    type: "function",
    name: "act",
    stateMutability: "payable",
    inputs: [
      { name: "gameId", type: "uint256" },
      { name: "action", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelOpenGame",
    stateMutability: "nonpayable",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimTimeout",
    stateMutability: "nonpayable",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "createGame",
    stateMutability: "payable",
    inputs: [{ name: "buyIn", type: "uint256" }],
    outputs: [{ name: "gameId", type: "uint256" }],
  },
  {
    type: "function",
    name: "dealHands",
    stateMutability: "nonpayable",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getPlayerState",
    stateMutability: "view",
    inputs: [
      { name: "gameId", type: "uint256" },
      { name: "account", type: "address" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "joined", type: "bool" },
          { name: "acted", type: "bool" },
          { name: "folded", type: "bool" },
          { name: "handDealt", type: "bool" },
          { name: "committed", type: "uint256" },
          { name: "roundStake", type: "uint256" },
          { name: "pendingWithdrawal", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getPrivateHand",
    stateMutability: "view",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [
      { name: "", type: "bytes32" },
      { name: "", type: "bytes32" },
    ],
  },
  {
    type: "function",
    name: "getPrivateScore",
    stateMutability: "view",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "getPublicGame",
    stateMutability: "view",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "playerOne", type: "address" },
          { name: "playerTwo", type: "address" },
          { name: "buyIn", type: "uint256" },
          { name: "pot", type: "uint256" },
          { name: "handCount", type: "uint8" },
          { name: "status", type: "uint8" },
          { name: "turn", type: "uint8" },
          { name: "actionCount", type: "uint8" },
          { name: "winner", type: "address" },
          { name: "playerOneHandDealt", type: "bool" },
          { name: "playerTwoHandDealt", type: "bool" },
          { name: "currentBet", type: "uint256" },
          { name: "playerOneRoundStake", type: "uint256" },
          { name: "playerTwoRoundStake", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "createdAt", type: "uint256" },
          { name: "updatedAt", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getWinnerHandle",
    stateMutability: "view",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "joinGame",
    stateMutability: "payable",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "nextGameId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "pendingWithdrawals",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "settleEncryptedWinner",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gameId", type: "uint256" },
      { name: "winnerSeatCode", type: "uint8" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
] as const;
